language: python
python:
  - '2.7'

install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq swig python-dev libxml2-dev libxmlsec1-dev
  - 'travis_retry pip install .'
  - 'travis_retry pip install -e ".[test]"'
